import {
  PROPERTY_MEDIA_BUCKET,
  PROPERTY_MEDIA_MAX_BYTES,
  type PropertyContentSnapshot,
} from '@/lib/property-content';

export function createLocalPropertyContentSnapshot(propertyId: string): PropertyContentSnapshot {
  return {
    property: {
      id: propertyId,
      organizationId: 'local-hamba-organization',
      name: 'Quarry Heights',
      area: 'Newlands East',
      description: 'Secure, practical rooms with convenient access to local transport and everyday amenities.',
      address: 'Newlands East, Durban',
      mapsUrl: 'https://maps.google.com/',
      publicPageUrl: 'https://hambatrading.com/properties/quarry-heights',
      photosUrl: 'https://photos.google.com/',
      pamphletUrl: 'https://hambatrading.com/pamphlets/quarry-heights.pdf',
      contactPrimary: 'Staff contact',
      contactSecondary: '',
      viewingInstructions: 'Staff confirms live availability and arranges the viewing.',
      parking: 'Confirm current parking options with staff.',
      features: ['Secure access', 'Convenient transport links'],
      descriptiveContentApproved: true,
    },
    rooms: [
      {
        id: 'local-room-01',
        propertyId,
        label: 'Room 01',
        description: 'A practical private room in the Quarry Heights property.',
        unitType: 'room',
        contactPrimary: '',
        contactSecondary: '',
        rentAmount: 0,
        depositAmount: 0,
        depositTerms: 'Staff confirms final terms.',
        occupancy: 'occupied',
        isAvailable: false,
        availableFrom: '',
        parking: '',
        ensuite: false,
        maxOccupants: 1,
        features: [],
        viewingInstructions: 'Staff confirms the viewing.',
        descriptiveContentApproved: true,
      },
    ],
    media: [
      {
        id: 'local-media-01',
        propertyId,
        unitId: '',
        kind: 'photo',
        sourceKind: 'external',
        storageBucket: PROPERTY_MEDIA_BUCKET,
        storagePath: '',
        externalUrl: 'https://photos.google.com/',
        caption: 'Quarry Heights approved property gallery',
        altText: 'Approved exterior and room photographs for Quarry Heights',
        displayOrder: 10,
        mimeType: 'text/uri-list',
        byteSize: null,
        isApproved: true,
        deliveryUrl: 'https://photos.google.com/',
      },
    ],
    imports: [],
    storage: {
      bucket: PROPERTY_MEDIA_BUCKET,
      isPrivate: true,
      maxBytes: PROPERTY_MEDIA_MAX_BYTES,
    },
  };
}
