-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  channel character varying DEFAULT 'whatsapp'::character varying,
  status character varying DEFAULT 'active'::character varying,
  last_message_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  phone_number character varying NOT NULL UNIQUE,
  name character varying,
  email character varying,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.knowledge_base (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category character varying NOT NULL,
  title character varying NOT NULL,
  content text NOT NULL,
  tags ARRAY,
  is_active boolean DEFAULT true,
  source_type text NOT NULL DEFAULT 'legacy'::text CHECK (source_type = ANY (ARRAY['file'::text, 'text'::text, 'website'::text, 'api'::text, 'database'::text, 'tool'::text, 'legacy'::text])),
  source_id text,
  source_name text NOT NULL DEFAULT ''::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT knowledge_base_pkey PRIMARY KEY (id)
);
CREATE TABLE public.knowledge_vectors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  knowledge_base_id uuid,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['file'::text, 'text'::text, 'website'::text, 'api'::text, 'database'::text, 'tool'::text, 'legacy'::text])),
  source_id text NOT NULL,
  source_name text NOT NULL DEFAULT ''::text,
  title text NOT NULL,
  content text NOT NULL,
  chunk_index integer NOT NULL DEFAULT 0 CHECK (chunk_index >= 0),
  chunk_count integer NOT NULL DEFAULT 1 CHECK (chunk_count > 0),
  embedding_model text NOT NULL DEFAULT 'text-embedding-3-small'::text,
  embedding_dimensions integer NOT NULL DEFAULT 768 CHECK (embedding_dimensions = 768),
  embedding extensions.vector(768) NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_vectors_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_vectors_source_chunk_key UNIQUE (source_type, source_id, chunk_index),
  CONSTRAINT knowledge_vectors_knowledge_base_id_fkey FOREIGN KEY (knowledge_base_id) REFERENCES public.knowledge_base(id) ON DELETE CASCADE
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  direction character varying NOT NULL,
  content text NOT NULL,
  message_type character varying DEFAULT 'text'::character varying,
  external_id character varying,
  delivery_status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  icon text NOT NULL DEFAULT 'ORG'::text,
  description text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.prompt_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL DEFAULT 'default'::character varying,
  system_prompt text NOT NULL DEFAULT 'You are a helpful assistant.'::text,
  temperature numeric NOT NULL DEFAULT 0.40 CHECK (temperature >= 0::numeric AND temperature <= 2::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  llm_provider character varying NOT NULL DEFAULT 'openai'::character varying,
  llm_model character varying NOT NULL DEFAULT 'gpt-5.4'::character varying,
  llm_api_key text NOT NULL DEFAULT ''::text,
  llm_base_url character varying NOT NULL DEFAULT ''::character varying,
  CONSTRAINT prompt_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  location text NOT NULL DEFAULT ''::text,
  icon text NOT NULL DEFAULT 'PR'::text,
  image_url text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.property_units (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid NOT NULL,
  label text NOT NULL,
  contact_primary text NOT NULL DEFAULT ''::text,
  contact_secondary text NOT NULL DEFAULT ''::text,
  rent_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (rent_amount >= 0::numeric),
  deposit_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (deposit_amount >= 0::numeric),
  occupancy_status text NOT NULL DEFAULT 'occupied'::text CHECK (occupancy_status = ANY (ARRAY['occupied'::text, 'vacant'::text])),
  is_blocked boolean NOT NULL DEFAULT false,
  parking text NOT NULL DEFAULT ''::text,
  ensuite boolean NOT NULL DEFAULT false,
  max_occupants integer NOT NULL DEFAULT 1 CHECK (max_occupants >= 0),
  is_available boolean NOT NULL DEFAULT false,
  features text[] NOT NULL DEFAULT '{}'::text[],
  expected_reference text NOT NULL DEFAULT ''::text,
  match_keywords text[] NOT NULL DEFAULT '{}'::text[],
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT property_units_pkey PRIMARY KEY (id),
  CONSTRAINT property_units_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT property_units_property_label_key UNIQUE (property_id, label)
);
CREATE TABLE public.property_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  unit_id uuid,
  kind text NOT NULL DEFAULT 'photo'::text CHECK (kind = ANY (ARRAY['photo'::text, 'floorplan'::text, 'video'::text, 'document'::text])),
  storage_path text NOT NULL DEFAULT ''::text,
  caption text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT property_media_pkey PRIMARY KEY (id),
  CONSTRAINT property_media_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT property_media_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.property_units(id) ON DELETE CASCADE,
  CONSTRAINT property_media_scope_check CHECK ((property_id IS NOT NULL) OR (unit_id IS NOT NULL))
);
CREATE TABLE public.property_chatbot_settings (
  property_id uuid NOT NULL,
  provider text NOT NULL DEFAULT 'openai'::text,
  model text NOT NULL DEFAULT 'gpt-5.4'::text,
  temperature numeric NOT NULL DEFAULT 0.40 CHECK (temperature >= 0::numeric AND temperature <= 2::numeric),
  system_prompt text NOT NULL DEFAULT ''::text,
  knowledge_sources ARRAY NOT NULL DEFAULT '{}'::text[],
  quick_replies ARRAY NOT NULL DEFAULT '{}'::text[],
  whatsapp_templates ARRAY NOT NULL DEFAULT '{}'::text[],
  retrieval_top_k integer NOT NULL DEFAULT 5 CHECK (retrieval_top_k > 0 AND retrieval_top_k <= 50),
  retrieval_similarity_threshold numeric(4,3) NOT NULL DEFAULT 0.200 CHECK (retrieval_similarity_threshold >= 0::numeric AND retrieval_similarity_threshold <= 1::numeric),
  retrieval_memory_mode text NOT NULL DEFAULT 'hybrid'::text CHECK (retrieval_memory_mode = ANY (ARRAY['hybrid'::text, 'rolling_window'::text, 'summary_memory'::text, 'retrieval_only'::text])),
  retrieval_history_window integer NOT NULL DEFAULT 20 CHECK (retrieval_history_window >= 1 AND retrieval_history_window <= 100),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT property_chatbot_settings_pkey PRIMARY KEY (property_id),
  CONSTRAINT property_chatbot_settings_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);
CREATE TABLE public.unit_payment_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  unit_id uuid NOT NULL,
  period_start date NOT NULL,
  expected_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (expected_amount >= 0::numeric),
  status text NOT NULL DEFAULT 'unpaid'::text CHECK (status = ANY (ARRAY['unpaid'::text, 'partial'::text, 'paid'::text, 'overdue'::text, 'blocked'::text, 'mismatch'::text])),
  is_blocked boolean NOT NULL DEFAULT false,
  note text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT unit_payment_periods_pkey PRIMARY KEY (id),
  CONSTRAINT unit_payment_periods_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.property_units(id) ON DELETE CASCADE,
  CONSTRAINT unit_payment_periods_unit_id_period_start_key UNIQUE (unit_id, period_start)
);
CREATE TABLE public.payment_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  property_id uuid,
  unit_id uuid,
  unit_payment_period_id uuid,
  bank_import_entry_id uuid,
  reference text NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (amount >= 0::numeric),
  received_at date NOT NULL,
  transaction_at timestamp with time zone,
  bank text NOT NULL DEFAULT ''::text,
  signed_off boolean NOT NULL DEFAULT false,
  signed_off_at timestamp with time zone,
  signed_off_by text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payment_references_pkey PRIMARY KEY (id),
  CONSTRAINT payment_references_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
  CONSTRAINT payment_references_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT payment_references_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.property_units(id) ON DELETE SET NULL,
  CONSTRAINT payment_references_unit_payment_period_id_fkey FOREIGN KEY (unit_payment_period_id) REFERENCES public.unit_payment_periods(id) ON DELETE SET NULL,
  CONSTRAINT payment_references_bank_import_entry_id_fkey FOREIGN KEY (bank_import_entry_id) REFERENCES public.bank_import_entries(id) ON DELETE SET NULL
);
CREATE TABLE public.bank_import_mailboxes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  email_address text NOT NULL UNIQUE,
  provider text NOT NULL DEFAULT 'gmail'::text CHECK (provider = ANY (ARRAY['gmail'::text])),
  label_filter text NOT NULL DEFAULT ''::text,
  subject_filter text NOT NULL DEFAULT ''::text,
  is_active boolean NOT NULL DEFAULT true,
  gmail_topic_name text NOT NULL DEFAULT ''::text,
  gmail_watch_expiration timestamp with time zone,
  last_history_id text NOT NULL DEFAULT ''::text,
  last_synced_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_import_mailboxes_pkey PRIMARY KEY (id),
  CONSTRAINT bank_import_mailboxes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE
);
CREATE TABLE public.bank_import_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mailbox_id uuid NOT NULL,
  gmail_message_id text NOT NULL,
  gmail_thread_id text NOT NULL DEFAULT ''::text,
  gmail_history_id text NOT NULL DEFAULT ''::text,
  message_from text NOT NULL DEFAULT ''::text,
  subject text NOT NULL DEFAULT ''::text,
  received_at timestamp with time zone,
  processed_at timestamp with time zone,
  import_status text NOT NULL DEFAULT 'pending'::text CHECK (import_status = ANY (ARRAY['pending'::text, 'processed'::text, 'failed'::text, 'ignored'::text])),
  error_message text NOT NULL DEFAULT ''::text,
  raw_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_import_messages_pkey PRIMARY KEY (id),
  CONSTRAINT bank_import_messages_mailbox_message_key UNIQUE (mailbox_id, gmail_message_id),
  CONSTRAINT bank_import_messages_mailbox_id_fkey FOREIGN KEY (mailbox_id) REFERENCES public.bank_import_mailboxes(id) ON DELETE CASCADE
);
CREATE TABLE public.bank_import_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  gmail_attachment_id text NOT NULL DEFAULT ''::text,
  file_name text NOT NULL,
  mime_type text NOT NULL DEFAULT 'application/pdf'::text,
  file_size_bytes bigint NOT NULL DEFAULT 0,
  file_sha256 text NOT NULL,
  storage_path text NOT NULL DEFAULT ''::text,
  parser_status text NOT NULL DEFAULT 'pending'::text CHECK (parser_status = ANY (ARRAY['pending'::text, 'parsed'::text, 'duplicate'::text, 'unsupported'::text, 'failed'::text])),
  statement_period_start date,
  statement_period_end date,
  parsed_at timestamp with time zone,
  parser_error text NOT NULL DEFAULT ''::text,
  raw_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_import_files_pkey PRIMARY KEY (id),
  CONSTRAINT bank_import_files_message_attachment_key UNIQUE (message_id, gmail_attachment_id),
  CONSTRAINT bank_import_files_file_sha256_key UNIQUE (file_sha256),
  CONSTRAINT bank_import_files_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.bank_import_messages(id) ON DELETE CASCADE
);
CREATE TABLE public.bank_import_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_id uuid NOT NULL,
  organization_id uuid,
  property_id uuid,
  payment_reference_id uuid,
  entry_fingerprint text NOT NULL,
  transaction_type text NOT NULL DEFAULT ''::text,
  transaction_date date,
  transaction_time text NOT NULL DEFAULT ''::text,
  destination_account_suffix text NOT NULL DEFAULT ''::text,
  reference text NOT NULL DEFAULT ''::text,
  description text NOT NULL DEFAULT ''::text,
  payer_name text NOT NULL DEFAULT ''::text,
  amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (amount >= 0::numeric),
  available_balance numeric(12,2),
  currency text NOT NULL DEFAULT 'ZAR'::text,
  source_page integer,
  source_index integer,
  raw_extracted_text text NOT NULL DEFAULT ''::text,
  raw_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_import_entries_pkey PRIMARY KEY (id),
  CONSTRAINT bank_import_entries_entry_fingerprint_key UNIQUE (entry_fingerprint),
  CONSTRAINT bank_import_entries_file_id_fkey FOREIGN KEY (file_id) REFERENCES public.bank_import_files(id) ON DELETE CASCADE,
  CONSTRAINT bank_import_entries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
  CONSTRAINT bank_import_entries_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE SET NULL,
  CONSTRAINT bank_import_entries_payment_reference_id_fkey FOREIGN KEY (payment_reference_id) REFERENCES public.payment_references(id) ON DELETE SET NULL
);
CREATE TABLE public.bank_import_property_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  property_id uuid,
  account_number_suffix text NOT NULL,
  property_name text NOT NULL DEFAULT ''::text,
  notes text NOT NULL DEFAULT ''::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_import_property_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT bank_import_property_mappings_organization_account_key UNIQUE (organization_id, account_number_suffix),
  CONSTRAINT bank_import_property_mappings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
  CONSTRAINT bank_import_property_mappings_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE SET NULL
);
CREATE TABLE public.bank_import_unit_match_hints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  property_id uuid,
  unit_id uuid,
  matcher_type text NOT NULL CHECK (matcher_type = ANY (ARRAY['reference_contains'::text, 'reference_equals'::text, 'reference_regex'::text, 'payer_name_contains'::text, 'amount_equals'::text])),
  matcher_value text NOT NULL DEFAULT ''::text,
  amount_value numeric(12,2),
  priority integer NOT NULL DEFAULT 100,
  notes text NOT NULL DEFAULT ''::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bank_import_unit_match_hints_pkey PRIMARY KEY (id),
  CONSTRAINT bank_import_unit_match_hints_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
  CONSTRAINT bank_import_unit_match_hints_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id) ON DELETE SET NULL,
  CONSTRAINT bank_import_unit_match_hints_unit_id_fkey FOREIGN KEY (unit_id) REFERENCES public.property_units(id) ON DELETE SET NULL
);
CREATE TABLE public.webhooks_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL,
  payload jsonb NOT NULL,
  status character varying DEFAULT 'processing'::character varying,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT webhooks_log_pkey PRIMARY KEY (id)
);
